image: node:10
stages:
  - setup
  - build
  - test

# Setup stage

prepare_job:
  stage: setup
  script:
    - npm install
  cache:
    key: node_modules
    policy: push
    paths:
      - node_modules

# Build stage

bundle_job:
  stage: build
  script:
    - npm install
    - npm run bundle
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules

# Test stage

lint_job:
  stage: test
  script:
    - npm install
    - npm run lint
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
